config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ========== ユーザー(user) ==========
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'index' => 'homes#index'

    resources :posts do
      resources :reviews, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
      collection do
        get 'search'
        get 'm_search' => 'posts#mobile_search'
        get 'weekly_rank' => 'posts#weekly_rank'
      end
    end

    get 'posts/:id/likes' => 'posts#like', as: 'like_index'
    get 'post/hashtag/:name' => 'posts#hashtag'

    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm' => 'contacts#confirm', as: 'contacts_confirm'
        post 'back' => 'contacts#back'
        get 'done' => 'contacts#done'
      end
    end

    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
        get 'bookmark' => 'users#bookmark', as: 'bookmark'
        get 'timeline' => 'users#timeline', as: 'timeline'
      end
    end
  end

  # # ========== 管理者(admin) ==========
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
  }

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    get 'search' => 'users#search'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :name, presence: true
  validates :subject, presence: true
  validates :message, presence: true

  enum subject: { question: 1, wantto_delete: 2, everything: 3 }
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: { maximum: 99 }
  has_many :post_hashtags
  has_many :posts, through: :post_hashtags
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :post_hashtags
  has_many :hashtags, through: :post_hashtags
  mount_uploader :image, ImageUploader

  validates :image, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def self.last_week
    Post.joins(:likes).where(likes: { created_at: 0.days.ago.prev_week..0.days.ago.prev_week(:sunday)}).group(:id).order("count(*) desc")
  end

  # 退会済の投稿は非表示
  def self.post_index
    Post.includes(:user).where(users: { is_deleted: false }).order(created_at: :desc)
  end

  def bookmarked_by(user)
    Bookmark.find_by(user_id: user.id, post_id: id)
  end

  after_create do
    post = Post.find_by(id: self.id)
    hashtags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    post.hashtags = []
    hashtags.uniq.map do |hashtag|
      # ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      post.hashtags << tag
    end
  end

  before_update do
    post = Post.find_by(id: self.id)
    post.hashtags.clear
    hashtags = self.body.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(hashname: hashtag.downcase.delete('#'))
      post.hashtags << tag
    end
  end
end

app/models/post_hashtag.rb
class PostHashtag < ApplicationRecord
  belongs_to :post
  belongs_to :hashtag
  with_options presence: true do
    validates :post_id
    validates :hashtag_id
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :review, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags

  validates :tag_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id",
                                      dependent: :destroy # class_name　ここから探す
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # through　中間テーブルを介してUserテーブルから探すイメージ
  # フォローしてくれたユーザーを中間テーブルをスルーしてUserテーブルから探す→follower_id（自分をフォローするユーザーID）参照
  has_many :followings, through: :relationships, source: :followed
  # フォローしているユーザーを中間テーブルをスルーしてUserテーブルから探す→followed_id（自分にフォローされるユーザーID）参照
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :reviews
  has_many :bookmarks

  USERNAME_REGEXP = /\A[a-zA-Z0-9][\w-]+\z/ # 半角英数字記号_-のみ
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # 有効なメールアドレス
  validates :name, presence: true, length: { maximum: 20 }
  validates :username, format: { with: USERNAME_REGEXP }, length: { maximum: 15 },
                       presence: true, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, presence: true, uniqueness: true
  # validates :password, length: { minimum: 6 }
  attachment :profile_image

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'Guest'
      user.username = 'guest3'
    end
  end

  def self.search(search)
    if search != ""
      User.where(['name LIKE(?) OR username LIKE(?) OR email LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Post.includes(:user).order('created_at DESC')
    end
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(body)
    body.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/post/hashtag/#{word.delete("#")}" }.html_safe
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div class="text-danger">
    <h3><%= "#{obj.errors.count}つのエラーがあります" %></h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
  <div class="copyright">
  	<p>© 2021 - Photo Recipe!</p>
  </div>
  <div class="sns">
    <div class="">
    <%= link_to new_contact_path do %>
  	  <i class="far fa-envelope" aria-hidden="true"></i>
  	<% end %>
  	<%= link_to "https://twitter.com/share?url=#{ request.url }/&text=スマホの写真を共有しよう！&hashtags=スマフォトレシピ", target: '_blank' do %>
  	  <i class="fab fa-twitter fa-fw" aria-hidden="true"></i>
  	<% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="pc-header" class="fixed-top sticky-top bg-white">
  <nav class="nav d-flex justify-content-between">
    <div class="logo">
      <%= link_to index_path, data: {"turbolinks" => false} do %>
        <%= image_tag 'logo.png', :size =>'232x45' %>
      <% end %>
    </div>
    <ul class="nav-items d-flex">
      <!--検索フォーム-->
      <li class="nav-item-search">
        <%= render 'layouts/search' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
          <span><%= link_to "Make a Recipe!", new_post_path, class: "nav-link" %></span>
        </li>
        <li class="nav-item">
          <span><%= link_to "Timeline", timeline_user_path(current_user.id), class: "nav-link" %></span>
        </li>
        <li class="nav-item">
          <span><%= link_to "Ranking", weekly_rank_posts_path, class: "nav-link" %></span>
        </li>
        <li class="nav-item">
          <span><%= link_to "Mypage", user_path(current_user), class: "nav-link" %></span>
        </li>
        <li class="nav-item">
          <span><%= link_to "Logout", destroy_user_session_path, class: "nav-link logout-test", method: :delete %></span>
        </li>
      <% elsif admin_signed_in? %>
        <li class="nav-item">
          <span><%= link_to "Users", admin_users_path, class: "nav-link" %></span>
        </li>
        <li class="nav-item">
          <span><%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %></span>
        </li>
      <% else %>
        <li class="nav-item">
          <span><%= link_to 'Guest Login!', users_guest_sign_in_path, method: :post, class: "nav-link" %></span>
        </li>
        <li class="nav-item">
          <span><%= link_to "Login", new_user_session_path, class: "nav-link login-test" %></span>
        </li>
        <li class="nav-item">
          <span><%= link_to "Signup", new_user_registration_path, class: "nav-link" %></span>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_mobile_footer.html.erb
<div id="fix-phone-under-menu" class="pc-none">
  <ul class="d-flex justify-content-start">
    <% if user_signed_in? %>
    <li class="mt-3">
      <%= link_to timeline_user_path(current_user), data: {"turbolinks" => false} do %>
        <i class="fas fa-stopwatch fa-2x"></i><br>
        <span class="iconname">Timeline</span>
      <% end %>
    </li>
    <li class="mt-3">
      <%= link_to index_path, data: {"turbolinks" => false} do %>
        <i class="fas fa-home fa-2x"></i><br>
        <span class="iconname">Home</span>
      <% end %>
    </li>
    <li class="mt-3">
      <%= link_to m_search_posts_path, data: {"turbolinks" => false} do %>
        <i class="fas fa-search fa-2x"></i><br>
        <span class="iconname">Search</span>
      <% end %>
    </li>
    <li class="mt-3">
      <%= link_to weekly_rank_posts_path, data: {"turbolinks" => false} do %>
        <i class="fas fa-crown fa-2x"></i><br>
        <span class="iconname">Ranking</span>
      <% end %>
    </li>
    <li class="mt-3">
      <%= link_to new_post_path, data: {"turbolinks" => false} do %>
        <i class="fas fa-utensils fa-2x"></i><br>
        <span class="iconname">Make!</span>
      <% end %>
    </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_mobile_header.html.erb
<div id="mobile-header">
  <div id="fix-phone-header-menu" class="pc-none sticky-top">
    <div class="logo-m">
      <%= link_to index_path, data: {"turbolinks" => false} do %>
        <%= image_tag 'logo.png', :size =>'220x40' %>
      <% end %>
    </div>
  </div>
  <!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <nav class="global-menu-sp">
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Mypage", user_path(current_user), data: {"turbolinks" => false} %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: {"turbolinks" => false} %></li>
        <li><%= link_to "Contact", new_contact_path, data: {"turbolinks" => false} %></li>
      <% elsif admin_signed_in? %>
        <li><%= link_to "Users", admin_users_path, data: {"turbolinks" => false} %></li>
        <li><%= link_to "Logout", destroy_admin_session_path, method: :delete, data: {"turbolinks" => false} %></li>
      <% else %>
        <li><%= link_to 'Guest Login!', users_guest_sign_in_path, method: :post, data: {"turbolinks" => false} %></li>
        <li><%= link_to "Signup", new_user_registration_path, data: {"turbolinks" => false} %></li>
        <li><%= link_to "Login", new_user_session_path, data: {"turbolinks" => false} %></li>
        <li><%= link_to "Contact", new_contact_path, data: {"turbolinks" => false} %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_search.html.erb
<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |f| %>
  <div class="search-button">
    <%= f.text_field :keyword, placeholder: "Search for Recipe!", class: "form-control" %>
    <%= button_tag :type => "submit", :class =>"btn btn-outline-primary" do %>
      <i class="fa fa-search"></i>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>スマフォトレシピ！</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--googleフォント-->
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <!--画像ポップアップ（lightbox2）-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <!--jscroll-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
    <!--meta-tags:url入力で説明文と画像表示-->
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.4/css/all.css">
    <%= render 'layouts/header' %>
    <%= render 'layouts/mobile_header' %>

    <div class="top-box">
      <div id="comments-error">
      <%= render 'layouts/flash' %>
      </div>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    <%= render 'layouts/mobile_footer' %>
  </body>
</html>