config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # ========== ユーザー(user) ==========
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'index' => 'homes#index'

    resources :posts do
      resources :reviews, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
      resources :bookmarks, only: [:create, :destroy]
      collection do
        get 'search'
        get 'm_search' => 'posts#mobile_search'
        get 'weekly_rank' => 'posts#weekly_rank'
      end
    end

    get 'posts/:id/likes' => 'posts#like', as: 'like_index'
    get 'post/hashtag/:name' => 'posts#hashtag'

    resources :contacts, only: [:new, :create] do
      collection do
        post 'confirm' => 'contacts#confirm', as: 'contacts_confirm'
        post 'back' => 'contacts#back'
        get 'done' => 'contacts#done'
      end
    end

    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
        get 'bookmark' => 'users#bookmark', as: 'bookmark'
        get 'timeline' => 'users#timeline', as: 'timeline'
      end
    end
  end

  # # ========== 管理者(admin) ==========
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
  }

  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    get 'search' => 'users#search'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id",
                                      dependent: :destroy # class_name　ここから探す
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # through　中間テーブルを介してUserテーブルから探すイメージ
  # フォローしてくれたユーザーを中間テーブルをスルーしてUserテーブルから探す→follower_id（自分をフォローするユーザーID）参照
  has_many :followings, through: :relationships, source: :followed
  # フォローしているユーザーを中間テーブルをスルーしてUserテーブルから探す→followed_id（自分にフォローされるユーザーID）参照
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :reviews
  has_many :bookmarks

  USERNAME_REGEXP = /\A[a-zA-Z0-9][\w-]+\z/ # 半角英数字記号_-のみ
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # 有効なメールアドレス
  validates :name, presence: true, length: { maximum: 20 }
  validates :username, format: { with: USERNAME_REGEXP }, length: { maximum: 15 },
                       presence: true, uniqueness: true
  validates :email, format: { with: VALID_EMAIL_REGEX }, presence: true, uniqueness: true
  # validates :password, length: { minimum: 6 }
  attachment :profile_image

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'Guest'
      user.username = 'guest3'
    end
  end

  def self.search(search)
    if search != ""
      User.where(['name LIKE(?) OR username LIKE(?) OR email LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Post.includes(:user).order('created_at DESC')
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: [:edit, :show, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render 'edit'
    end
  end

  def search
    redirect_to admin_users_path if params[:user_keyword] == ""
    @users = User.search(params[:user_keyword])
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :profile_image, :introduction, :is_deleted)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user_index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-10 mx-auto">
      <h3>ユーザー一覧</h3>
      <br>
      <li class="nav-item">
        <%= form_with(url: admin_search_path, local: true, method: :get, class: "search-form") do |f| %>
          <div class="search-button">
            <%= f.text_field :user_keyword, placeholder: "ユーザーを検索する", class: "form-control" %>
            <%= button_tag :type => "submit", :class =>"btn btn-primary" do %>
              <i class="fa fa-search"></i>
            <% end %>
          </div>
        <% end %>
      </li>
      <br><br>
      <table class="table table-hover table-inverse table-responsive-md mt-3">
        <thead class="table-active">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>ユーザーネーム</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% users.each do |user| %>
            <tr>
              <td>
                <%= user.id %>
              </td>
              <td>
                <%= link_to admin_user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <%= user.username %>
              </td>
              <td>
                <%= user.email %>
              </td>
              <td>
                <% if user.is_deleted == true %>
                  <p class="text-secondary">退会</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/_users_index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-md-10 mx-auto">
      <h3>ユーザー 一覧</h3>
      <br>
      <%= render 'users_search' %>
      <br><br>
      <table class="table table-hover table-inverse table-responsive-md mt-3">
        <thead class="table-active">
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% users.each do |user| %>
            <tr>
              <td>
                <%= user.id %>
              </td>
              <td>
                <%= link_to admin_user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <%= user.username %>
              </td>
              <td>
                <%= user.email %>
              </td>
              <td>
                <% if user.is_deleted == true %>
                  <p class="text-secondary">退会</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/_users_search.html.erb
<li class="nav-item">
  <%= form_with(url: admin_search_path, local: true, method: :get, class: "search-form") do |f| %>
    <div class="search-button">
      <%= f.text_field :user_keyword, placeholder: "ユーザーを検索する", class: "form-control" %>
      <%= button_tag :type => "submit", :class =>"btn btn-primary" do %>
        <i class="fa fa-search"></i>
      <% end %>
    </div>
  <% end %>
</li>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="col-12 mx-auto">
    <%= form_with model: @user, url: admin_user_path, local: true do |f| %>
      <%= render 'layouts/error', obj: @user %>
      <div class="profile-shape">
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size: "60x60" %>
      </div><br>
      <div class="form-group">
      <%= f.label "プロフィール画像" %><br>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>

      <div class="form-group">
      <%= f.label "名前" %>
      <%= f.text_field :name, autofocus: true, placeholder: "令和道子", class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label "ユーザーネーム" %>
      <%= f.text_field :username, autofocus: true, placeholder: "半角英数字記号（- , _)", class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label "紹介文" %>
      <%= f.text_field :introduction, autofocus: true, placeholder: "初めまして！", class: "form-control" %>
      </div>

      <div class="form-group">
      <%= f.label "メールアドレス" %>
      <%= f.email_field :email, autofocus: true, placeholder: "sample@example.com", class: "form-control" %>
      </div>
      <br>
      <div>
      <%= f.label "会員ステータス", class: "mr-5 mb-5"%>
      <%= f.radio_button :is_deleted, "false" %>有効 　　<%= f.radio_button :is_deleted, "true" %>退会
      </div>

      <%= f.submit "編集内容を保存", class: "btn btn-outline-info w-100" %>
      <br><br>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= render 'users_index', users: @users %>

app/views/admin/users/search.html.erb
<%= render 'users_index', users: @users %>

app/views/admin/users/show.html.erb
<div class="container">
    <div class="row mt-3 mb-3">
      <div class="col-md-6 mx-auto">
        <h3><%= @user.name %>さんの会員詳細</h3>
        <table class="table table-inversemt-3">
          <tr>
            <td class="mt-2" style="width: 30%;">会員ID</td>
            <td style="width: 70%;"><%= @user.id %></td>
          </tr>
          <tr>
            <td class="mt-2">名前</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <td class="mt-2">ユーザーネーム</td>
            <td><%= @user.username %></td>
          </tr>
          <tr>
            <td class="mt-2">メールアドレス</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <td class="mt-2">会員ステータス</td>
            <td>
              <% if @user.is_deleted == true %>
               <p class="text-secondary mt-2">退会</p>
              <% else %>
                <p class="text-success mt-2">有効</p>
             <% end %>
            </td>
          </tr>
        </table>
      <div class="d-flex justify-content-center">
        <%= link_to "編集する", edit_admin_user_path, class: 'btn btn-success col-4 mr-3' %>
        <%= link_to "トップに戻る", admin_root_path, class: 'btn btn-primary col-4' %>
      </div>
    </div>
  </div>
</div>